version: '3.8'

volumes:
  postgres_data:

networks:
  app_network:

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-13-alpine}
    container_name: postgres_petshop
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-petshop}
    ports:
      - '${POSTGRES_PUBLIC_PORT:-5433}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  petshop:
    image: petshop:${PETSHOP_VERSION:-latest}
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: petshop
    restart: ${RESTART_POLICY:-unless-stopped}
    depends_on:
      - postgres
    ports:
      - "${PUBLIC_PORT:-3333}:3000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-petshop}
      - DATABASE_HOST=${DB_HOST:-postgres}
      - DATABASE_PORT=${POSTGRES_PUBLIC_PORT:-5433}
      - DATABASE_USER=${POSTGRES_USER:-postgres}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - DATABASE_NAME=${POSTGRES_DB:-petshop}
    networks:
      - app_network
